In [20]:
import numpy as np
arr = np.array([[2,4,5], [6,7,8]])

print(arr)
print(type(arr))
print(np.size(arr))
print(np.shape(arr))

[[2 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>
6
(2, 3)


In [19]:
import numpy as np
arr = np.array([[2,4,5], [6,7,8]])

ones = np.ones((2,2))
print(ones)

zeros = np.zeros((2,3))
print(zeros)

diag = np.eye(3)
print(diag)

ran = np.random.random((3,3))
print(ran)

typ = arr.dtype
print(typ)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.5417182  0.69203422 0.14737469]
 [0.82902146 0.52046386 0.75572287]
 [0.29166689 0.18475507 0.29431782]]
int64


In [27]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.array([[2,4,5], [6,7,8]])

print(arr[0:4])
print(arr[0:5:2])
print(arr[:3])
print(arr1[0:2,1:3])

[1 2 3 4]
[1 3 5]
[1 2 3]
[[4 5]
 [7 8]]


In [29]:
import numpy as np 

arr = np.ones((5,5))
arr[1:4,1:4]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
